spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_center?nullCatalogMeansCurrent=true&serverTimezone=UTC
    hikari:
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
